/**
 * IdeaForge AI – Cloudinary Upload Service
 * ─────────────────────────────────────────────────────────────
 * Uploads AI-generated images to Cloudinary for permanent CDN hosting.
 * DALL-E 3 URLs expire after ~1 hour — Cloudinary gives permanent links.
 *
 * API credentials are read from process.env via config/env.js — never hardcoded.
 */

import { v2 as cloudinary } from "cloudinary";
import { config } from "../config/env.js";

// ─────────────────────────────────────────
// Configure Cloudinary SDK
// ─────────────────────────────────────────

if (config.cloudinary.isConfigured) {
    cloudinary.config({
        cloud_name: config.cloudinary.cloudName,
        api_key: config.cloudinary.apiKey,
        api_secret: config.cloudinary.apiSecret,
        secure: true,
    });
    console.log("☁️  Cloudinary configured successfully.");
} else {
    console.warn(
        "⚠️  Cloudinary not configured — images will use direct API URLs (may expire)."
    );
}

// ─────────────────────────────────────────
// Upload Image URL to Cloudinary
// ─────────────────────────────────────────

/**
 * Uploads an image from a URL (e.g., DALL-E URL) to Cloudinary.
 * Returns a permanent CDN URL.
 *
 * @param {string} imageUrl   - Temporary URL from OpenAI/Stability
 * @param {string} publicId   - Cloudinary public_id (filename without extension)
 * @returns {Promise<string>} - Permanent Cloudinary CDN URL
 */
export async function uploadImageFromUrl(imageUrl, publicId) {
    if (!config.cloudinary.isConfigured) {
        // Graceful fallback: return original URL
        console.warn("Cloudinary not configured — returning original URL.");
        return imageUrl;
    }

    const result = await cloudinary.uploader.upload(imageUrl, {
        public_id: publicId,
        folder: "ideaforge-ai/generations",
        overwrite: true,
        resource_type: "image",
        transformation: [
            { quality: "auto:best" },
            { fetch_format: "auto" },
        ],
    });

    return result.secure_url;
}

// ─────────────────────────────────────────
// Upload Base64 Image to Cloudinary
// ─────────────────────────────────────────

/**
 * Uploads a base64-encoded image (e.g., from Stability AI) to Cloudinary.
 *
 * @param {string} base64DataUri - Full data URI: "data:image/png;base64,..."
 * @param {string} publicId      - Cloudinary public_id
 * @returns {Promise<string>}    - Permanent Cloudinary CDN URL
 */
export async function uploadBase64Image(base64DataUri, publicId) {
    if (!config.cloudinary.isConfigured) {
        console.warn("Cloudinary not configured — returning base64 data URI.");
        return base64DataUri;
    }

    const result = await cloudinary.uploader.upload(base64DataUri, {
        public_id: publicId,
        folder: "ideaforge-ai/generations",
        overwrite: true,
        resource_type: "image",
    });

    return result.secure_url;
}

// ─────────────────────────────────────────
// Generate Watermarked URL
// ─────────────────────────────────────────

/**
 * Returns a Cloudinary transformation URL that overlays
 * the "Generated by IdeaForge AI" watermark text.
 *
 * @param {string} cloudinaryUrl - Already-uploaded Cloudinary URL
 * @returns {string}             - URL with watermark transformation
 */
export function addWatermarkTransformation(cloudinaryUrl) {
    if (!config.cloudinary.isConfigured || !cloudinaryUrl.includes("cloudinary.com")) {
        return cloudinaryUrl; // Can't apply transformations on non-Cloudinary URLs
    }

    // Insert transformation before /upload/
    return cloudinaryUrl.replace(
        "/upload/",
        "/upload/l_text:Arial_22_bold:Generated%20by%20IdeaForge%20AI,co_white,o_80,g_south_east,x_10,y_10/"
    );
}
