import toast from "react-hot-toast";

export default function ShareButtons({ result }) {
    if (!result) return null;

    const { imageUrl, sceneTitle, story, prompt } = result;

    // ── LinkedIn Share
    const shareLinkedIn = () => {
        const text = encodeURIComponent(
            `🤖✨ I just created "${sceneTitle}" using IdeaForge AI!\n\n"${story}"\n\nTry it yourself → https://ideaforge.ai`
        );
        window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent("https://ideaforge.ai")}&summary=${text}`, "_blank");
    };

    // ── Twitter/X Share
    const shareTwitter = () => {
        const text = encodeURIComponent(
            `✨ "${sceneTitle}" — created with IdeaForge AI!\n\n${story}\n\nTurn your ideas into visuals → https://ideaforge.ai\n\n#IdeaForgeAI #AIArt #AI`
        );
        window.open(`https://twitter.com/intent/tweet?text=${text}`, "_blank");
    };

    // ── Instagram: No direct API — copy to clipboard
    const shareInstagram = () => {
        const text = `✨ "${sceneTitle}"\n\n${story}\n\nGenerated by IdeaForge AI → ideaforge.ai\n\n#IdeaForgeAI #AIArt #AIGenerated`;
        navigator.clipboard.writeText(text).then(() => {
            toast.success("Caption copied! Open Instagram and paste it.", { duration: 4000 });
        });
    };

    // ── Copy Prompt
    const copyPrompt = () => {
        navigator.clipboard.writeText(prompt).then(() => {
            toast.success("✅ AI prompt copied to clipboard!");
        });
    };

    // ── Download Image
    const downloadImage = async () => {
        try {
            const response = await fetch(imageUrl);
            const blob = await response.blob();
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `ideaforge-${sceneTitle.replace(/\s+/g, "-").toLowerCase()}.png`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            toast.success("🖼️ Image downloaded!");
        } catch {
            // Fallback: open in new tab
            window.open(imageUrl, "_blank");
        }
    };

    return (
        <div className="flex flex-wrap gap-2 mt-4">
            {/* Download */}
            <button id="share-download" onClick={downloadImage} className="share-btn share-btn-download">
                📥 Download
            </button>

            {/* Copy Prompt */}
            <button id="share-copy-prompt" onClick={copyPrompt} className="share-btn share-btn-copy">
                📋 Copy Prompt
            </button>

            {/* LinkedIn */}
            <button id="share-linkedin" onClick={shareLinkedIn} className="share-btn share-btn-linkedin">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                </svg>
                LinkedIn
            </button>

            {/* Twitter/X */}
            <button id="share-twitter" onClick={shareTwitter} className="share-btn share-btn-twitter">
                <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.748l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                </svg>
                Twitter
            </button>

            {/* Instagram */}
            <button id="share-instagram" onClick={shareInstagram} className="share-btn"
                style={{ background: "linear-gradient(135deg, #405de6, #5851db, #833ab4, #c13584, #e1306c, #fd1d1d)", color: "white" }}>
                📸 Instagram
            </button>
        </div>
    );
}
